# -*- coding: utf-8 -*-
"""5 noviembre prueba0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UENhUE6SL39g1nnuAxfq4n8fkIRFiczA
"""

ruta="https://raw.githubusercontent.com/marinlopabi/Temas-Selectos-PQ-AD-Python/refs/heads/main/Datos/CEMEXCPO.csv"

df = pd.read_csv(ruta)
df.head()

import pandas as pd

df['Date']= pd.to_datetime(df['Date'])

df = df.set_index("Date")
df

df.info()

df=df.set_index("Date")
df

import pandas as pd

df.idxmax()# encontrar el valor más alto de índice

df.idxmin()#encontrar el bvalor más bajo de índice

import matplotlib.pyplot as plt

plt.figure(figsize=(16,8), dpi=150)#fig size es en pulgadas u dpi es la resolución que va a llevar(crea la figura)
plt.plot(df.index,df["Close"], lw=2.5, color="black",label="precio de cierre")
plt.xlabel("fecha",fontsize=18, labelpad=10)# titulo tamaño del título
plt.ylabel("precio($)", fontsize=18, labelpad=10)
plt.title("precio de cierre-cemex", fontsize=22, fontweight="bold", pad=15)
plt.grid(alpha=0.3)#sirve para desvanecer o que tan nitida queremos la transparecia
plt.tick_params(labelsize=14)#añadir argumentos en los ejes
plt.legend(fontsize=14)
plt.tight_layout()#para acomodar o distribuir las cosas
plt.show()#correr la gráfica de mabnera más limpia

import matplotlib.pyplot as plt
import matplotlib.dates as mdates

# Crear figura
plt.figure(figsize=(16, 8), dpi=150)

# Línea principal del precio de cierre
plt.plot(df.index, df["Close"], lw=2.5, color="#1f77b4", label="Precio de cierre")

# Sombreado del área bajo la curva para resaltar la tendencia
plt.fill_between(df.index, df["Close"], color="#1f77b4", alpha=0.1)

# Etiquetas y título
plt.xlabel("Fecha", fontsize=16, labelpad=10)
plt.ylabel("Precio ($)", fontsize=16, labelpad=10)
plt.title("Evolución del precio de cierre - Cemex", fontsize=22, fontweight="bold", pad=20)

# Formato del eje X para fechas
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m"))
plt.gca().xaxis.set_major_locator(mdates.MonthLocator(interval=3))  # una etiqueta cada 3 meses
plt.xticks(rotation=45, ha="right")  # rotar las fechas para mejor lectura

# Cuadrícula más suave y elegante
plt.grid(which='major', color='gray', linestyle='--', alpha=0.3)
plt.grid(which='minor', color='gray', linestyle=':', alpha=0.1)

# Ajustes de ejes
plt.tick_params(labelsize=12, colors="dimgray")
plt.legend(fontsize=14, loc="upper left", frameon=False)

# Fondo de la figura más suave
plt.gca().set_facecolor("#f9f9f9")
plt.tight_layout()

# Mostrar la gráfica
plt.show()

"""ejercicio de walmart"""

ruta="https://raw.githubusercontent.com/marinlopabi/Temas-Selectos-PQ-AD-Python/refs/heads/main/Datos/WALMEX.csv"#siempre ponerentrecomillas el link

df=pd.read_csv(ruta)
df.head()

df.info()

df["Date"]=pd.to_datetime(df["Date"])

df.info()

df=df.set_index("Date")
df

"""subir archivos y enviar la liga del github"""